---

- hosts: all
  become: true
  tasks:

  - name: Update Ubuntu Servers
    tags: always
    apt:
      upgrade: dist   
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: Install Apache for Web Servers
    tags: apache, web_server
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"      
